# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

matrix:
  include:
    - python: 2.7
      env: PIP_INSTALL=1
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

virtualenv:
  system_site_packages: true

before_install:
  - uname -a
  - free -m
  - df -h
  - python -V

install:
  - echo $PIP_INSTALL
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors nose numpy Cython scipy
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install python-tables python-pyside
  - pip install pyqtgraph
  - python setup.py -q install

before_script:
  # We need to create a (fake) display on Travis, let's use a funny resolution
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  # Test installing with pip
  - pip install .

  # check we can import pypore
  - pushd /
  - echo "import pypore" | python
  - popd

  # run the tests
  - python setup.py test


notifications:
  email: false

