# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# whitelist
branches:
  only:
    - master
    - develop

matrix:
  include:
    - python: "2.7"
      env:
        - TESTMODE=full
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

before_install:
  - uname -a
  - free -m
  - df -h
  - python -V
  - pip -V
  - sudo apt-get update -qq

install:
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  # apt Cython version too small, must use pip
  - sudo apt-get install libblas-dev libatlas-dev liblapack-dev
  # apt Scipy/Numpy versions too small, use pip
  - pip install --no-index --find-links https://parkin.github.io/python-wheelhouse/ numpy
  - pip install --no-index --find-links https://parkin.github.io/python-wheelhouse/ scipy
  - pip install scipy numpy
  - pip install nose;
  - sudo apt-get install -qq python${TRAVIS_PYTHON_VERSION}-dev;
  - sudo apt-get install libpython${TRAVIS_PYTHON_VERSION};
  - if [ "${TESTMODE}" == "full" ]; then pip install coveralls; fi;
  - python setup.py -q install

script:
  # Test installing with pip
  - pip install .

  # check we can import pypore
  - pushd /
  - echo "import pypore" | python
  - popd

  # Build C extensions next to .c files
  - python setup.py build_ext --inplace

  # run the tests
  - if [ "${TESTMODE}" == "full" ]; then
      coverage run --source=src setup.py test;
    else
      nosetests;
    fi;

after_success:
  - if [ "${TESTMODE}" == "full" ]; then coveralls; fi;

notifications:
  email: false
