# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

matrix:
  include:
    - python: 2.7
      env: PIP_INSTALL=1
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

virtualenv:
  system_site_packages: true

before_install:
  - uname -a
  - free -m
  - df -h
  - python -V
  - travis_retry sudo apt-get update

install:
  - echo $PIP_INSTALL
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors nose numpy Cython scipy
  - sudo apt-get install python-tables
  - python setup.py install

script:
  - python setup.py test

notifications:
  email: false

