# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
      env:
        - USE_APT=true
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
    - python: "pypy"

virtualenv:
  system_site_packages: true

before_install:
  - uname -a
  - free -m
  - df -h
  - python -V

install:
  - travis_retry sudo apt-get install libhdf5-serial-dev
  - if [ "${USE_APT}" == "true" ]; then
      if [ "or", [ ${PYTHON}, "2.6", ${PYTHON}, "2.7"]]; then
        travis_retry sudo apt-get install -qq -y python-numpy python-scipy;
        travis_retry sudo apt-get install python-pyside python-nose;
      else
        travis_retry sudo apt-get install -qq -y python3-numpy python3-scipy;
        travis_retry sudo apt-get install python3-pyside python3-nose;
      fi;
    else
      pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors nose numpy scipy;
      pip install numexpr;
      pip install tables;
      pip install sphinx==1.1.3;
      sudo apt-get install build-essential git cmake libqt4-dev libphonon-dev python2.7-dev libxml2-dev libxslt1-dev qtmobility-dev;
      pip install pyside;
      pip insatll --upgrade sphinx;
    fi;

  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  # apt Cython version too small, must use pip
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors Cython
  - pip install pyqtgraph
  - python setup.py -q install

before_script:
  # We need to create a (fake) display on Travis, let's use a funny resolution
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  # Test installing with pip
  - pip install .

  # check we can import pypore
  - pushd /
  - echo "import pypore" | python
  - popd

  # run the tests
  - python setup.py test

notifications:
  email: false

